### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by kevinsimper** [AmritaMaloo/hyf-javascript1#1]
Hi Amrita

Thanks for making the homework! 👍 I am really impressed by the website, it looks really good and it is fun to use!

You solved the homework correctly and made a great use of the different jQuery functions!

One improvement you could have made was to use the `<code>` tag, that would have helped you with the line breaks and then you would not have needed the `<br>` tags. https://github.com/AmritaMaloo/hyf-javascript1/blob/master/week1/index.html#L58-L76

You will read more code than you write and therefore code formatting is important, you should strive to indent the code in a consistent manner, here for example the code stands a bit strange https://github.com/AmritaMaloo/hyf-javascript1/blob/master/week1/infinity_Compare.js

Look at Airbnb coding style guideline or a automatic tool like https://prettier.io/playground/

**Comment by AmritaMaloo** [comment]
Hi Kevin,

Thanks to you for the feedback and your time to analyse the homework. I would take care of the points mentioned above in the further assignments.
Thank you again !!!
